risk:
  confidence_threshold: 0.65
  max_drawdown: 0.05
  max_position_size: 1000
  trading_hours:
    start: "09:15"
    end: "15:15"
  global_context:
    vix_threshold: 20.0
    gift_nifty_gap: 0.01
    us_futures_gap: 0.01
    asian_markets_gap: 0.01
    usdinr_change: 0.005
    sector_rank_threshold: 3
